sudo: true
# Choose a lightweight base image; we provide our own build tools.
language: c
# GHC depends on GMP. You can add other dependencies here as well.
addons:
  apt:
    packages:
    - libgmp-dev
    - wget

before_install:
- wget https://dl.influxdata.com/influxdb/releases/influxdb_0.13.0_amd64.deb
- sudo dpkg -i influxdb_0.13.0_amd64.deb
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
- sudo influxd &
- sleep 20

# The different configurations we want to test.
env:
- TRAVIS_STACK_ARGS=""
- TRAVIS_STACK_ARGS="--resolver lts"
- TRAVIS_STACK_ARGS="--resolver lts-2"
- TRAVIS_STACK_ARGS="--resolver nightly"
 
install:
    - stack setup --no-terminal
    - stack build --only-snapshot --no-terminal

script:
    - stack $TRAVIS_STACK_ARGS --no-terminal --install-ghc test --haddock --pedantic

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack
