sudo: true
# Choose a lightweight base image; we provide our own build tools.
language: c
# GHC depends on GMP. You can add other dependencies here as well.
addons:
  apt:
    packages:
    - libgmp-dev

before_install:
- wget https://dl.influxdata.com/influxdb/releases/influxdb_0.13.0_amd64.deb
- sudo dpkg -i influxdb_0.13.0_amd64.deb
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
    - stack setup --no-terminal
    - stack build --only-snapshot --no-terminal

script:
    - influxd &
    - stack --no-terminal --install-ghc test --haddock --pedantic

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack
